#!/usr/bin/env bash
# Installing nginx on a server and setting it up to return hello world as it's default

sudo apt-get update -y

sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
touch /var/www/html/index.html
chown $USER:$USER /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html

sudo systemctl restart nginx
