#!/usr/bin/bash
# Installing nginx on a server and setting it up to return hello world as it's default

sudo apt-get update -y
sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.nginx-debian.html

systemctl restart nginx
