#!/usr/bin/env bash
# Installing nginx on a server and setting it up to return hello world as it's default

sudo apt-get update -y
sudo apt-get install nginx -y

sudo apt-get update -y
sudo apt-get install nginx -y

sudo chown -R $USER:$USER /var/www
sudo echo 'Hello World!' > /var/www/html/index.html
sudo systemctl restart nginx
