#!/usr/bin/env bash
# Installing nginx on a server and setting it up to redirect when hit with /redirect_me 

sudo apt-get update -y

sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"

touch /var/www/html/default/index.html
echo "Hello World!" | sudo tee -a /var/www/html/index.html

loc_reloc='\\tlocation /redirect_me {\n\t\treturn 301 http://www.google.com;\n\t}'
sudo sed -i "47i $loc_reloc" /etc/nginx/sites-available/default

sudo service nginx restart
