#!/usr/bin/env bash

# Installing nginx on a server and setting it up to redirect when hit with /redirect_me 

sudo apt-get update -y

sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"

loc_reloc='location /redirect_me {\n\treturn 301 http://www.google.com\n}'
sudo sed -i 's/# pass PHP scripts to FastCGI server/'"$loc_reloc"'/g' /etc/nginx/nginx.conf

sudo service nginx restart
