#!/usr/bin/env bash
# Installing nginx on a server and setting it up to return hello world as it's default

sudo apt-get update -y

sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"

#create home page with hello world
touch /var/www/html/index.html
chown $USER:$USER /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html


#redirection
loc_reloc='\\tlocation /redirect_me {\n\t\treturn 301 http://www.google.com;\n\t}'


sudo sed -i "47i $loc_reloc" /etc/nginx/sites-available/default
#error handling
touch /var/www/html/error_404
echo "Ceci n'est pas une page." | sudo tee /var/www/html/error_404
error_404='\\n\terror_page 404 /error_404;'
sudo sed -i "24i $error_404" /etc/nginx/sites-available/default

#adding custom header
sudo sed -i "21i add_header X-Served-By \$hostname" /etc/nginx/sites-available/default

sudo systemctl restart nginx
