#!/usr/bin/env bash
#-Create a file and put $$ in it
#-Print a string infinitely
#-trap sigterm, sigint



trap "echo 'I hate the kill command' && rm /var/run/myscript.pid && exit " SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm -f /var/run/myscript.pid && exit" SIGQUIT



echo $$ > /var/run/myscript.pid

for ((;;));
do
echo "To infinity and beyond"
sleep 5;
done
