#!/usr/bin/env bash
# printing numbers from 1-20 except superstitious bad luck numbers

a=1

while (( a < 21 ));
do

case "$a" in
 "4")
echo "$a" 
echo "bad luck from china"
;;

9)
echo "$a"
echo "bad luck from japan"
;;

17)
echo "$a"
echo "bad luck from italy"
;;

*)
echo "$a"
;;

esac

((a++))
done
